=== sophykk/PSEMolDyn-GroupE/src/xsd/Simulation.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="simulation">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="simulationParams" type="simulationParamsType"/>
                <xs:element name="parallelizationStrategyParam" type="parallelizationStrategyType" minOccurs="0"/>
                <xs:element name="linkedCellParams" type="linkedCellParamsType" minOccurs="0"/>
                <xs:element name="thermostat" type="thermostatType" minOccurs="0"/>
                <xs:element name="cuboid" type="cuboidType" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="sphere" type="sphereType" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="simulationParamsType">
        <xs:sequence>
            <xs:element name="endTime" type="xs:double"/>
            <xs:element name="deltaT" type="xs:double"/>
            <xs:element name="modelType" type="xs:string"/>
            <xs:element name="containerType" type="xs:string"/>
            <xs:element name="plotInterval" type="xs:int"/>
            <xs:element name="objectType" type="xs:string"/>
            <xs:element name="checkpointing" type="xs:boolean"/>
            <xs:element name="useParallelization" type="xs:boolean"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="parallelizationStrategyType">
        <xs:sequence>
            <xs:element name="parallelizationStrategy" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="linkedCellParamsType">
        <xs:sequence>
            <xs:element name="domainSize" type="domainParam"/>
            <xs:element name="cutoffRadius" type="xs:double"/>
            <xs:element name="boundaryConditions" type="boundaryConditionsType"/>
            <xs:element name="gravitationalAcceleration" type="xs:double"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="cuboidType">
        <xs:sequence>
            <xs:element name="position" type="positionType"/>
            <xs:element name="velocity" type="velocityType"/>
            <xs:element name="mass" type="xs:double"/>
            <xs:element name="grid" type="gridParam"/>
            <xs:element name="spacing" type="xs:double"/>
            <xs:element name="sigma" type="xs:double"/>
            <xs:element name="epsilon" type="xs:double"/>
            <xs:element name="gravitationalAcceleration" type="xs:double"/>
            <xs:element name="type" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="thermostatType">
        <xs:sequence>
            <xs:element name="initialTemperature" type="xs:double"/>
            <xs:element name="targetTemperature" minOccurs="0" type="xs:double"/>
            <xs:element name="maxTemperatureChange" minOccurs="0" type="xs:double"/>
            <xs:element name="thermostatInterval" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="sphereType">
        <xs:sequence>
            <xs:element name="position" type="positionType"/>
            <xs:element name="velocity" type="velocityType"/>
            <xs:element name="mass" type="xs:double"/>
            <xs:element name="spacing" type="xs:double"/>
            <xs:element name="radius" type="xs:double"/>
            <xs:element name="sigma" type="xs:double"/>
            <xs:element name="epsilon" type="xs:double"/>
            <xs:element name="gravitationalAcceleration" type="xs:double"/>
            <xs:element name="type" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="positionType">
        <xs:sequence>
            <xs:element name="x" type="xs:double"/>
            <xs:element name="y" type="xs:double"/>
            <xs:element name="z" type="xs:double"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="velocityType">
        <xs:sequence>
            <xs:element name="v" type="xs:double"/>
            <xs:element name="w" type="xs:double"/>
            <xs:element name="z" type="xs:double"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="gridParam">
        <xs:sequence>
            <xs:element name="Nx" type="xs:int"/>
            <xs:element name="Ny" type="xs:int"/>
            <xs:element name="Nz" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="domainParam">
        <xs:sequence>
            <xs:element name="Lx" type="xs:double"/>
            <xs:element name="Ly" type="xs:double"/>
            <xs:element name="Lz" type="xs:double"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="boundaryConditionsType">
        <xs:sequence>
            <xs:element name="left" type="xs:string"/>
            <xs:element name="up" type="xs:string"/>
            <xs:element name="right" type="xs:string"/>
            <xs:element name="down" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== sophykk/PSEMolDyn-GroupE/input/w5t4.xml
<?xml version="1.0"?>
<simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="../src/xsd/Simulation.xsd">
    <simulationParams>
        <endTime>500</endTime>
        <deltaT> 0.0005</deltaT>
        <modelType>lennardJones</modelType>
        <containerType>linkedCells</containerType>
        <plotInterval>10</plotInterval>
        <objectType>cuboid</objectType>
        <checkpointing>false</checkpointing>
        <useParallelization>false</useParallelization>
    </simulationParams>

    <linkedCellParams>
        <domainSize>
            <Lx>30</Lx>
            <Ly>30</Ly>
            <Lz>12</Lz>
        </domainSize>
        <cutoffRadius>2.75</cutoffRadius>
        <boundaryConditions>
            <left>o</left>
            <up>p</up>
            <right>o</right>
            <down>p</down>
            <front>p</front>
            <back>p</back>
        </boundaryConditions>
        <gravitationalAcceleration>-0.8</gravitationalAcceleration>
        <isMembrane>false</isMembrane>
    </linkedCellParams>

    <thermostat>
        <initialTemperature>40</initialTemperature>
        <thermostatInterval>10</thermostatInterval>
    </thermostat>

    <cuboid>
        <position>
            <x>1</x>
            <y>0.5</y>
            <z>0.5</z>
        </position>
        <velocity>
            <v>0</v>
            <w>0</w>
            <z>0</z>
        </velocity>
        <mass>1.0</mass>
        <grid>
            <Nx>2</Nx>
            <Ny>30</Ny>
            <Nz>12</Nz>
        </grid>
        <spacing>1.0</spacing>
        <sigma>1.1</sigma>
        <epsilon>2.0</epsilon>
        <gravitationalAcceleration>-0.8</gravitationalAcceleration>
        <type>1</type>
        <isWall>true</isWall>
    </cuboid>

    <cuboid>
        <position>
            <x>27.2</x>
            <y>0.5</y>
            <z>0.5</z>
        </position>
        <velocity>
            <v>0</v>
            <w>0</w>
            <z>0</z>
        </velocity>
        <mass>1.0</mass>
        <grid>
            <Nx>2</Nx>
            <Ny>30</Ny>
            <Nz>12</Nz>
        </grid>
        <spacing>1.0</spacing>
        <sigma>1.1</sigma>
        <epsilon>2.0</epsilon>
        <gravitationalAcceleration>-0.8</gravitationalAcceleration>
        <type>2</type>
        <isWall>true</isWall>
    </cuboid>

    <cuboid>
        <position>
            <x>3.2</x>
            <y>0.6</y>
            <z>0.6</z>
        </position>
        <velocity>
            <v>0</v>
            <w>0</w>
            <z>0</z>
        </velocity>
        <mass>1.0</mass>
        <grid>
            <Nx>20</Nx>
            <Ny>25</Ny>
            <Nz>10</Nz>
        </grid>
        <spacing>1.2</spacing>
        <sigma>1.0</sigma>
        <epsilon>1.0</epsilon>
        <gravitationalAcceleration>-0.8</gravitationalAcceleration>
        <type>3</type>
        <isWall>false</isWall>
    </cuboid>
</simulation>

=== sophykk/PSEMolDyn-GroupE/input/w4t3.xml
<?xml version="1.0"?>
<simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="../src/xsd/Simulation.xsd">
    <simulationParams>
        <endTime>40</endTime>
        <deltaT> 0.0005</deltaT>
        <modelType>lennardJones</modelType>
        <containerType>linkedCells</containerType>
        <plotInterval>100</plotInterval>
        <objectType>cuboid</objectType>
        <checkpointing>true</checkpointing>
    </simulationParams>

    <linkedCellParams>
        <domainSize>
            <Lx>303</Lx>
            <Ly>180</Ly>
            <Lz>1</Lz>
        </domainSize>
        <cutoffRadius>3</cutoffRadius>
        <boundaryConditions>
            <left>p</left>
            <up>r</up>
            <right>p</right>
            <down>r</down>
        </boundaryConditions>
        <gravitationalAcceleration>-12.44</gravitationalAcceleration>
    </linkedCellParams>

    <thermostat>
        <initialTemperature>0.5</initialTemperature>
        <thermostatInterval>1000</thermostatInterval>
    </thermostat>

    <cuboid>
        <position>
            <x>1.5</x>
            <y>2</y>
            <z>0</z>
        </position>
        <velocity>
            <v>0</v>
            <w>0</w>
            <z>0</z>
        </velocity>
        <mass>1.0</mass>
        <grid>
            <Nx>250</Nx>
            <Ny>50</Ny>
            <Nz>1</Nz>
        </grid>
        <spacing>1.2</spacing>
        <sigma>1.2</sigma>
        <epsilon>1.0</epsilon>
        <gravitationalAcceleration>-12.44</gravitationalAcceleration>
        <type>1</type>
    </cuboid>
    
    <sphere>
        <position>
            <x>150</x>
            <y>150</y>
            <z>0</z>
        </position>
        <velocity>
            <v>0</v>
            <w>0</w>
            <z>0</z>
        </velocity>
        <mass>1</mass>
        <spacing>1.2</spacing>
        <radius>20</radius>
        <sigma>1.2</sigma>
        <epsilon>1.0</epsilon>
        <gravitationalAcceleration>-12.44</gravitationalAcceleration>
        <type>2</type>
    </sphere>
</simulation>

=== sophykk/PSEMolDyn-GroupE/input/w3t4.xml
<?xml version="1.0"?>
<simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="../src/xsd/Simulation.xsd">
    <simulationParams>
        <endTime>10</endTime>
        <deltaT> 0.00005</deltaT>
        <modelType>lennardJones</modelType>
        <containerType>linkedCells</containerType>
        <plotInterval>10</plotInterval>
    </simulationParams>

    <lennardJonesForceParams>
        <sigma>1.0</sigma>
        <epsilon>5.0</epsilon>
    </lennardJonesForceParams>

    <linkedCellParams>
        <domainSize>
            <Lx>120</Lx>
            <Ly>50</Ly>
            <Lz>1</Lz>
        </domainSize>
        <cutoffRadius>3.0</cutoffRadius>
        <boundaryCondition>r</boundaryCondition>
    </linkedCellParams>
    
    <sphere>
        <position>
            <x>60</x>
            <y>25</y>
            <z>0</z>
        </position>
        <velocity>
            <v>0</v>
            <w>-10</w>
            <z>0</z>
        </velocity>
        <mass>1.0</mass>
        <spacing>1.1225</spacing>
        <radius>15</radius>
        <type>1</type>
    </sphere>
</simulation>

=== sophykk/PSEMolDyn-GroupE/input/w4t2test.xml
<?xml version="1.0"?>
<simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="../src/xsd/Simulation.xsd">
    <simulationParams>
        <endTime>25</endTime>
        <deltaT> 0.0005</deltaT>
        <modelType>lennardJones</modelType>
        <containerType>linkedCells</containerType>
        <plotInterval>10</plotInterval>
        <objectType>cuboid</objectType>
        <checkpointing>false</checkpointing>
    </simulationParams>
    
    <linkedCellParams>
        <domainSize>
            <Lx>63</Lx>
            <Ly>36</Ly>
            <Lz>1</Lz>
        </domainSize>
        <cutoffRadius>2.5</cutoffRadius>
        <boundaryConditions>
            <left>p</left>
            <up>r</up>
            <right>p</right>
            <down>r</down>
        </boundaryConditions>
        <gravitationalAcceleration>1</gravitationalAcceleration>
    </linkedCellParams>

    <thermostat>
        <initialTemperature>40</initialTemperature>
        <thermostatInterval>1000</thermostatInterval>
    </thermostat>

    <cuboid>
        <position>
            <x>0.6</x>
            <y>2</y>
            <z>0</z>
        </position>
        <velocity>
            <v>0</v>
            <w>0</w>
            <z>0</z>
        </velocity>
        <mass>1.0</mass>
        <grid>
            <Nx>50</Nx>.
            <Ny>14</Ny>
            <Nz>1</Nz>
        </grid>
        <spacing>1.2</spacing>
        <sigma>1.0</sigma>
        <epsilon>1.0</epsilon>
        <gravitationalAcceleration>1</gravitationalAcceleration>
        <type>1</type>
    </cuboid>

    <cuboid>
        <position>
            <x>0.6</x>
            <y>19</y>
            <z>0</z>
        </position>
        <velocity>
            <v>0</v>
            <w>0</w>
            <z>0</z>
        </velocity>
        <mass>2.0</mass>
        <grid>
            <Nx>50</Nx>
            <Ny>14</Ny>
            <Nz>1</Nz>
        </grid>
        <spacing>1.2</spacing>
        <sigma>0.9412</sigma>
        <epsilon>1.0</epsilon>
        <gravitationalAcceleration>1</gravitationalAcceleration>
        <type>2</type>
    </cuboid>
</simulation>

=== sophykk/PSEMolDyn-GroupE/input/4000p.xml
<?xml version="1.0"?>
<simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="../src/xsd/Simulation.xsd">
    <simulationParams>
        <endTime>5</endTime>
        <deltaT>0.0002</deltaT>
        <modelType>lennardJones</modelType>
        <containerType>linkedCells</containerType>
        <plotInterval>10</plotInterval>
        <objectType>cuboid</objectType>
    </simulationParams>

    <lennardJonesForceParams>
        <sigma>1.0</sigma>
        <epsilon>5.0</epsilon>
    </lennardJonesForceParams>

    <linkedCellParams>
        <domainSize>
            <Lx>180</Lx>
            <Ly>90</Ly>
            <Lz>1</Lz>
        </domainSize>
        <cutoffRadius>3.0</cutoffRadius>
        <boundaryConditions>
            <left>o</left>
            <up>o</up>
            <right>o</right>
            <down>o</down>
        </boundaryConditions>
    </linkedCellParams>

    <cuboid>
        <position>
            <x>20.0</x>
            <y>20.0</y>
            <z>0.0</z>
        </position>
        <velocity>
            <v>0.0</v>
            <w>0.0</w>
            <z>0.0</z>
        </velocity>
        <mass>1.0</mass>
        <grid>
            <Nx>64</Nx>
            <Ny>64</Ny>
            <Nz>1</Nz>
        </grid>
        <spacing>1.1225</spacing>
        <type>1</type>
    </cuboid>

    <cuboid>
        <position>
            <x>70.0</x>
            <y>60.0</y>
            <z>0.0</z>
        </position>
        <velocity>
            <v>0.0</v>
            <w>-10.0</w>
            <z>0.0</z>
        </velocity>
        <mass>1.0</mass>
        <grid>
            <Nx>64</Nx>
            <Ny>64</Ny>
            <Nz>1</Nz>
        </grid>
        <spacing>1.1225</spacing>
        <type>2</type>
    </cuboid>
</simulation>

=== sophykk/PSEMolDyn-GroupE/input/task2.xml
<?xml version="1.0"?>
<simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="../src/xsd/Simulation.xsd">

    <cuboid>
        <position>
            <x>0.0</x>
            <y>0.0</y>
            <z>0.0</z>
        </position>
        <velocity>
            <v>0.0</v>
            <w>0.0</w>
            <z>0.0</z>
        </velocity>
        <mass>1.0</mass>
        <grid>
            <Nx>40</Nx>
            <Ny>8</Ny>
            <Nz>1</Nz>
        </grid>
        <spacing>1.1225</spacing>
        <type>1</type>
    </cuboid>

    <cuboid>
        <position>
            <x>15.0</x>
            <y>15.0</y>
            <z>0.0</z>
        </position>
        <velocity>
            <v>0.0</v>
            <w>-10.0</w>
            <z>0.0</z>
        </velocity>
        <mass>1.0</mass>
        <grid>
            <Nx>8</Nx>
            <Ny>8</Ny>
            <Nz>1</Nz>
        </grid>
        <spacing>1.1225</spacing>
        <type>2</type>
    </cuboid>
</simulation>
